export const productData = {
  'agro-chemicals': [
    {
      category: 'Agro Chemicals',
      title: 'Ammonium Sulphate',
      description:
        'A nitrogen-rich fertilizer that promotes plant growth and soil acidity regulation.',
      image: '/productImage1.JPG',
    },
    {
      category: 'Agro Chemicals',
      title: 'Glyphosate',
      description: 'A broad-spectrum herbicide used to control weeds and unwanted vegetation.',
      image: '/productImage2.JPG',
    },
    {
      category: 'Agro Chemicals',
      title: 'Paraquat',
      description: 'A fast-acting, non-selective herbicide effective for weed and grass control.',
      image: '/productImage3.JPG',
    },
    {
      category: 'Agro Chemicals',
      title: 'Potassium Nitrate',
      description:
        'A fertilizer that provides essential potassium and nitrogen for plant health and yield improvement.',
      image: '/productImage4.JPG',
    },
  ], 
  plastics: [
    {
      category: 'Plastics',
      title: 'Calcium Carbonate Micronized',
      description:
        'A fine mineral powder used as a filler to enhance plastic strength and durability.',
      image: '/productImage5.JPG',
    },
    {
      category: 'Plastics',
      title: 'DOP (Dioctyl Phthalate)',
      description: 'A plasticizer that increases flexibility and softness in plastic products.',
      image: '/productImage6.JPG',
    },
    {
      category: 'Plastics',
      title: 'Organic Pigments',
      description: 'Colorants used to provide vibrant and stable colors in plastic manufacturing.',
      image: '/productImage7.JPG',
    },
    {
      category: 'Plastics',
      title: 'Stearic Acid',
      description:
        'A lubricant and stabilizer that improves plastic processing and prevents brittleness.',
      image: '/productImage8.JPG',
    },
    {
      category: 'Plastics',
      title: 'Titanium Dioxide',
      description:
        'A white pigment that enhances brightness, opacity, and UV resistance in plastics.',
      image: '/productImage5.JPG',
    },
  ],
  food: [
    {
      category: 'Food',
      title: 'Ammonium Bicarbonate',
      description: 'A leavening agent used in baking to make dough rise.',
      image: '/productImage1.JPG',
    },
    {
      category: 'Food',
      title: 'Ascorbic Acid',
      description: 'Also known as Vitamin C, used as an antioxidant and preservative.',
      image: '/productImage2.JPG',
    },
    {
      category: 'Food',
      title: 'Aspartame',
      description: 'A low-calorie artificial sweetener used in sugar-free products.',
      image: '/productImage3.JPG',
    },
    {
      category: 'Food',
      title: 'Bleaching Earth',
      description: 'Used in refining edible oils to remove impurities and color.',
      image: '/productImage4.JPG',
    },
    {
      category: 'Food',
      title: 'Calcium Carbide',
      description: 'A chemical used to ripen fruits artificially.',
      image: '/productImage5.JPG',
    },
    {
      category: 'Food',
      title: 'Calcium Carbonate Micronized',
      description: 'A food additive used as an acidity regulator and calcium supplement.',
      image: '/productImage6.JPG',
    },
    {
      category: 'Food',
      title: 'Calcium Propionate',
      description: 'A preservative that prevents mold growth in baked goods.',
      image: '/productImage7.JPG',
    },
    {
      category: 'Food',
      title: 'Cellulosic Thickener',
      description: 'A food additive used to improve texture and consistency.',
      image: '/productImage8.JPG',
    },
    {
      category: 'Food',
      title: 'Citric Acid Anhydrous',
      description: 'A flavor enhancer and preservative found in soft drinks and candies.',
      image: '/productImage9.JPG',
    },
    {
      category: 'Food',
      title: 'Citric Acid Monohydrate',
      description: 'A crystalline form of citric acid used as a preservative and acidulant.',
      image: '/productImage12.JPG',
    },
    {
      category: 'Food',
      title: 'Corn Starch',
      description: 'A thickening agent used in soups, sauces, and desserts.',
      image: '/productImage17.JPG',
    },
    {
      category: 'Food',
      title: 'Dextrose Monohydrate',
      description: 'A sweetener and energy source found in sports drinks and processed foods.',
      image: '/productImage12.JPG',
    },
    {
      category: 'Food',
      title: 'Ethanol 96.3% (Edible)',
      description: 'A food-grade alcohol used in beverages and flavor extracts.',
      image: '/productImage13.JPG',
    },
    {
      category: 'Food',
      title: 'Fat Filled Milk Powder',
      description: 'A milk powder alternative enriched with vegetable fats.',
      image: '/productImage25.JPG',
    },
    {
      category: 'Food',
      title: 'Flavours',
      description: 'Natural or artificial compounds used to enhance food taste.',
      image: '/productImage15.JPG',
    },
    {
      category: 'Food',
      title: 'Fructose',
      description: 'A natural sugar found in fruits and used as a sweetener in foods and beverages.',
      image: '/productImage16.JPG',
    },
    {
      category: 'Food',
      title: 'Full Cream Milk Powder',
      description: 'A dairy product with a high-fat content for creamy taste and texture.',
      image: '/productImage17.JPG',
    },
    {
      category: 'Food',
      title: 'Glycerine 99%',
      description: 'A humectant used in food to retain moisture and improve texture.',
      image: '/productImage18.JPG',
    },
    {
      category: 'Food',
      title: 'Guar Gum',
      description: 'A natural thickener and stabilizer used in sauces, ice creams, and baked goods.',
      image: '/productImage25.JPG',
    },
    {
      category: 'Food',
      title: 'Hexane',
      description: 'A solvent used in oil extraction from seeds like soybeans.',
      image: '/productImage20.JPG',
    },
    {
      category: 'Food',
      title: 'Industrial Margarine',
      description: 'A processed fat used as a butter substitute in baking and cooking.',
      image: '/productImage21.JPG',
    },
    {
      category: 'Food',
      title: 'Liquid Glucose',
      description: 'A sweet syrup used in candies, beverages, and processed foods.',
      image: '/productImage22.JPG',
    },
    {
      category: 'Food',
      title: 'Malto Dextrine',
      description: 'A carbohydrate derived from starch, used as a thickener and energy source.',
      image: '/productImage23.JPG',
    },
    {
      category: 'Food',
      title: 'Menthol Crystal',
      description: 'A cooling agent used in confectionery and breath fresheners.',
      image: '/productImage24.JPG',
    },
    {
      category: 'Food',
      title: 'Methylene Chloride',
      description: 'A solvent used in caffeine extraction for decaffeinated coffee.',
      image: '/productImage25.JPG',
    },
],
  'oil-field': [
    {
      category: 'Oil Field',
      title: 'Bentonite',
      description: 'A clay mineral used in drilling muds to improve viscosity and filtration control.',
      image: '/productImage25.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Biocides',
      description: 'Chemicals used to control bacterial growth in drilling and production fluids.',
      image: '/productImage26.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Bentonite Extender',
      description: 'A chemical additive that enhances the performance of bentonite in drilling fluids.',
      image: '/productImage27.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Calcium Carbonate',
      description: 'A weighting agent used in drilling fluids to control formation pressures.',
      image: '/productImage28.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Calcium Chloride 94%',
      description: 'A brine solution used for wellbore stability and as a drilling fluid additive.',
      image: '/productImage5.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Caustic Soda Pearls 99%',
      description: 'A strong alkali used to maintain pH levels in drilling fluids.',
      image: '/productImage6.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Cellulosic Thickener',
      description: 'A viscosity enhancer that stabilizes drilling fluids.',
      image: '/productImage29.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Defoamers',
      description: 'Additives used to reduce foam formation in drilling muds and production processes.',
      image: '/productImage30.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Diethylene Glycol (DEG)',
      description: 'A hydrate inhibitor used in gas dehydration and pipeline operations.',
      image: '/productImage9.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Drilling Detergents',
      description: 'Surfactants used to reduce drilling torque and improve mud flow.',
      image: '/productImage31.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Guar Gum',
      description: 'A natural polymer used to enhance viscosity in drilling fluids.',
      image: '/productImage32.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Hydrated Lime',
      description: 'A pH control agent that stabilizes drilling fluids and prevents corrosion.',
      image: '/productImage12.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Hydrochloric Acid',
      description: 'Used in well stimulation to dissolve formations and improve oil flow.',
      image: '/productImage13.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Lubricants',
      description: 'Reduce friction in drilling operations to improve efficiency and protect equipment.',
      image: '/productImage33.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Methanol',
      description: 'A hydrate inhibitor used in natural gas production to prevent pipeline blockages.',
      image: '/productImage34.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Monoethylene Glycol (MEG)',
      description: 'A dehydration agent used in natural gas processing.',
      image: '/productImage35.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Pipe Coating - Modified Alkyd Varnish',
      description: 'A protective coating to prevent corrosion in oilfield pipelines.',
      image: '/productImage36.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Poly Anionic Cellulose (PAC)',
      description: 'A filtration control additive used in drilling and completion fluids.',
      image: '/productImage37.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Potassium Chloride',
      description: 'A clay stabilizer that prevents swelling in water-sensitive formations.',
      image: '/productImage38.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Primary Emulsifiers',
      description: 'Agents that help form stable oil-based drilling fluids.',
      image: '/productImage39.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Soda Ash Light',
      description: 'A pH regulator that removes calcium and stabilizes drilling mud.',
      image: '/productImage40.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Sodium Bicarbonate',
      description: 'Used to neutralize acidic drilling fluids and control pH levels.',
      image: '/productImage41.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Sulfonated Asphalt',
      description: 'A shale stabilizer and fluid loss control agent in drilling operations.',
      image: '/productImage42.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Triethylene Glycol (TEG)',
      description: 'A dehydration agent used in natural gas processing.',
      image: '/productImage43.JPG',
    },
    {
      category: 'Oil Field',
      title: 'Xanthan Gum',
      description: 'A high-viscosity polymer used to improve drilling fluid performance.',
      image: '/productImage40.JPG',
    },
  ],
  'water-treatment': [
    {
      category: 'Water Treatment',
      title: 'Aluminium Sulphate',
      description: 'A coagulant used in water purification to remove impurities and clarify water.',
      image: '/productImage35.JPG',
    },
    {
      category: 'Water Treatment',
      title: 'Calcium Hypochlorite',
      description:
        'A disinfectant and bleaching agent used in water treatment to kill bacteria and sanitize..',
      image: '/productImage36.JPG',
    },
    {
      category: 'Water Treatment',
      title: 'Ferric Chloride',
      description:
        'A coagulating agent used in water treatment to remove suspended solids and control turbidity.',
      image: '/productImage12.JPG',
    },
    {
      category: 'Water Treatment',
      title: 'Ferrous Sulphate',
      description:
        'A reducing agent used in water treatment for phosphate removal and coagulation.',
      image: '/productImage13.JPG',
    },
    {
      category: 'Water Treatment',
      title: 'Hydrated Lime',
      description:
        'Used to adjust water pH and remove impurities, including heavy metals and organic matter',
      image: '/productImage14.JPG',
    },
  ],
}
